name = "SEM_Wave_1d"
uuid = "70bd66a2-9068-46a7-95d7-34e5be5a448e"
authors = ["EBmn <elliotbckmn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
